export const UsosCFDI = [
  { key: "G01", use: "Adquisición de mercancías" },
  { key: "G02", use: "Devoluciones, descuentos o bonificaciones" },
  { key: "G03", use: "Gastos en general" },
  { key: "I01", use: "Construcciones" },
  { key: "I02", use: "Mobiliario y equipo de oficina por inversiones" },
  { key: "I03", use: "Equipo de transporte" },
  { key: "I04", use: "Equipo de cómputo y accesorios" },
  { key: "I05", use: "Dados, troqueles, moldes, matrices y herramental" },
  { key: "I06", use: "Comunicaciones telefónicas" },
  { key: "I07", use: "Comunicaciones satelitales" },
  { key: "I08", use: "Otra maquinaría y equipo" },
  { key: "D01", use: "Honorarios médicos, dentales y gastos hospitalarios" },
  { key: "D02", use: "Gastos médicos por inacapacidad o discapacidad" },
  { key: "D03", use: "Gastos funerales" },
  { key: "D04", use: "Donativos" },
  {
    key: "D05",
    use: "Intereses reales ffectivamente pagados por créditos hipotecarios (Casa Habitación)",
  },
  { key: "D06", use: "Aportaciones voluntarias al SAR" },
  { key: "D07", use: "Primas por seguros de gastos médicos" },
  { key: "D08", use: "Gastos por transportación escolar" },
  {
    key: "D09",
    use: "Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones",
  },
  { key: "D10", use: "Pagos por servicios educativos" },
  { key: "S01", use: "Sin efectos fiscales" },
  { key: "CP01", use: "Pagos" },
  { key: "CN01", use: "Nómina" },
];
